/// Turns Unicode's emoji-test.txt into the emoji table the picker reads.
///
///     dart run tool/gen_emoji.dart
///
/// Reads tool/emoji-test.txt (checked in, from
/// https://unicode.org/Public/emoji/latest/emoji-test.txt) and writes
/// lib/ui/emoji/emoji_data.dart. Pure Dart, no Flutter, so it runs anywhere.
library;

import 'dart:io';

/// Emoji newer than this may not be in the platforms' fonts yet, and would
/// draw as empty boxes. Raise it as iOS and macOS catch up.
const maxEmojiVersion = 17.0;

class ParsedEmoji {
  const ParsedEmoji(this.char, this.name);
  final String char;
  final String name;
}

class ParsedGroup {
  ParsedGroup(this.name);
  final String name;
  final emoji = <ParsedEmoji>[];
}

final _line = RegExp(
  r'^([0-9A-F ]+?)\s*;\s*fully-qualified\s*#\s*(\S+)\s+E(\d+\.\d+)\s+(.+)$',
);

/// Skin-tone modifiers U+1F3FB–1F3FF. Variants carrying one wait for a
/// skin tone setting.
bool _hasSkinTone(String codepoints) => codepoints
    .split(' ')
    .any((c) => ['1F3FB', '1F3FC', '1F3FD', '1F3FE', '1F3FF'].contains(c));

/// The picker's groups, in Unicode's order: fully-qualified emoji only, no
/// Component group (skin tones and hair parts are not emoji to pick), no
/// skin-tone variants, and nothing newer than [maxVersion].
List<ParsedGroup> parseEmojiTest(
  String text, {
  double maxVersion = maxEmojiVersion,
}) {
  final groups = <ParsedGroup>[];
  ParsedGroup? current;
  for (final raw in text.split('\n')) {
    final line = raw.trim();
    if (line.startsWith('# group:')) {
      final name = line.substring('# group:'.length).trim();
      current = name == 'Component' ? null : ParsedGroup(name);
      if (current != null) groups.add(current);
      continue;
    }
    final match = _line.firstMatch(line);
    if (current == null || match == null) continue;
    final version = double.parse(match.group(3)!);
    if (version > maxVersion || _hasSkinTone(match.group(1)!)) continue;
    current.emoji.add(ParsedEmoji(match.group(2)!, match.group(4)!.trim()));
  }
  return groups.where((g) => g.emoji.isNotEmpty).toList();
}

String _quote(String s) =>
    "'${s.replaceAll(r'\', r'\\').replaceAll("'", r"\'").replaceAll(r'$', r'\$')}'";

/// The Dart source of lib/ui/emoji/emoji_data.dart.
String renderEmojiTable(List<ParsedGroup> groups) {
  final out = StringBuffer()
    ..writeln(
      '// GENERATED by tool/gen_emoji.dart from Unicode emoji-test.txt.',
    )
    ..writeln('// Do not edit by hand; rerun the tool.')
    ..writeln()
    ..writeln("import 'emoji.dart';")
    ..writeln()
    ..writeln('const emojiGroups = <EmojiGroup>[');
  for (final group in groups) {
    out.writeln('  EmojiGroup(${_quote(group.name)}, [');
    for (final e in group.emoji) {
      out.writeln('    Emoji(${_quote(e.char)}, ${_quote(e.name)}),');
    }
    out.writeln('  ]),');
  }
  out.writeln('];');
  return out.toString();
}

void main() {
  final source = File('tool/emoji-test.txt').readAsStringSync();
  final groups = parseEmojiTest(source);
  File('lib/ui/emoji/emoji_data.dart')
    ..createSync(recursive: true)
    ..writeAsStringSync(renderEmojiTable(groups));
  final count = groups.fold(0, (n, g) => n + g.emoji.length);
  stdout.writeln('wrote $count emoji in ${groups.length} groups');
}
