/// Turns Unicode's emoji-test.txt into the emoji table the picker reads,
/// with the `:shortcodes:` the composer knows each one by.
///
///     dart run tool/gen_emoji.dart
///
/// Reads tool/emoji-test.txt (checked in, from
/// https://unicode.org/Public/emoji/latest/emoji-test.txt) and writes
/// lib/ui/emoji/emoji_data.dart. Shortcodes are GitHub's (gemoji), as the
/// markdown package ships them, plus one made from each CLDR name so emoji
/// newer than GitHub's list still have one. Pure Dart, no Flutter, so it
/// runs anywhere.
library;

import 'dart:io';

import 'package:markdown/markdown.dart' show emojis;

/// Emoji newer than this may not be in the platforms' fonts yet, and would
/// draw as empty boxes. Raise it as iOS and macOS catch up.
const maxEmojiVersion = 17.0;

class ParsedEmoji {
  ParsedEmoji(this.char, this.name);
  final String char;
  final String name;

  /// Filled in by [attachShortcodes]: GitHub's first, then the CLDR one.
  final shortcodes = <String>[];
}

class ParsedGroup {
  ParsedGroup(this.name);
  final String name;
  final emoji = <ParsedEmoji>[];
}

final _line = RegExp(
  r'^([0-9A-F ]+?)\s*;\s*fully-qualified\s*#\s*(\S+)\s+E(\d+\.\d+)\s+(.+)$',
);

/// Skin-tone modifiers U+1F3FB–1F3FF. Variants carrying one wait for a
/// skin tone setting.
bool _hasSkinTone(String codepoints) => codepoints
    .split(' ')
    .any((c) => ['1F3FB', '1F3FC', '1F3FD', '1F3FE', '1F3FF'].contains(c));

/// The picker's groups, in Unicode's order: fully-qualified emoji only, no
/// Component group (skin tones and hair parts are not emoji to pick), no
/// skin-tone variants, and nothing newer than [maxVersion].
List<ParsedGroup> parseEmojiTest(
  String text, {
  double maxVersion = maxEmojiVersion,
}) {
  final groups = <ParsedGroup>[];
  ParsedGroup? current;
  for (final raw in text.split('\n')) {
    final line = raw.trim();
    if (line.startsWith('# group:')) {
      final name = line.substring('# group:'.length).trim();
      current = name == 'Component' ? null : ParsedGroup(name);
      if (current != null) groups.add(current);
      continue;
    }
    final match = _line.firstMatch(line);
    if (current == null || match == null) continue;
    final version = double.parse(match.group(3)!);
    if (version > maxVersion || _hasSkinTone(match.group(1)!)) continue;
    current.emoji.add(ParsedEmoji(match.group(2)!, match.group(4)!.trim()));
  }
  return groups.where((g) => g.emoji.isNotEmpty).toList();
}

/// GitHub's table writes some emoji without the variation selector that
/// Unicode's fully-qualified form carries (⚗ for ⚗️); they are the same
/// emoji.
String _bare(String char) => char.replaceAll('️', '');

/// "grinning face with smiling eyes" → grinning_face_with_smiling_eyes;
/// "flag: Japan" → flag_japan.
String cldrShortcode(String name) => name
    .toLowerCase()
    .replaceAll(RegExp('[’\']'), '')
    .replaceAll(RegExp(r'[^a-z0-9+]+'), '_')
    .replaceAll(RegExp(r'^_+|_+$'), '');

/// Gives each emoji its shortcodes: every GitHub name for it, then one made
/// from its CLDR name. A shortcode means exactly one emoji, so a CLDR one
/// that is already GitHub's, or that two names would share ("keycap: *"
/// and "keycap: #"), is left out. GitHub names for emoji the picker does
/// not have are dropped: they would insert something that may not draw.
void attachShortcodes(List<ParsedGroup> groups, Map<String, String> github) {
  final byChar = <String, ParsedEmoji>{
    for (final g in groups)
      for (final e in g.emoji) _bare(e.char): e,
  };
  final taken = <String>{};
  for (final code in github.keys.toList()..sort()) {
    final emoji = byChar[_bare(github[code]!)];
    if (emoji == null) continue;
    emoji.shortcodes.add(code);
    taken.add(code);
  }
  final cldr = <String, List<ParsedEmoji>>{};
  for (final g in groups) {
    for (final e in g.emoji) {
      final code = cldrShortcode(e.name);
      if (code.isEmpty || taken.contains(code)) continue;
      (cldr[code] ??= []).add(e);
    }
  }
  for (final MapEntry(key: code, value: owners) in cldr.entries) {
    if (owners.length == 1) owners.single.shortcodes.add(code);
  }
}

String _quote(String s) =>
    "'${s.replaceAll(r'\', r'\\').replaceAll("'", r"\'").replaceAll(r'$', r'\$')}'";

/// The Dart source of lib/ui/emoji/emoji_data.dart.
String renderEmojiTable(List<ParsedGroup> groups) {
  final out = StringBuffer()
    ..writeln(
      '// GENERATED by tool/gen_emoji.dart from Unicode emoji-test.txt and',
    )
    ..writeln("// GitHub's emoji names. Do not edit by hand; rerun the tool.")
    ..writeln()
    ..writeln("import 'emoji.dart';")
    ..writeln()
    ..writeln('const emojiGroups = <EmojiGroup>[');
  for (final group in groups) {
    out.writeln('  EmojiGroup(${_quote(group.name)}, [');
    for (final e in group.emoji) {
      final codes = e.shortcodes.isEmpty
          ? ''
          : ', [${e.shortcodes.map(_quote).join(', ')}]';
      out.writeln('    Emoji(${_quote(e.char)}, ${_quote(e.name)}$codes),');
    }
    out.writeln('  ]),');
  }
  out.writeln('];');
  return out.toString();
}

void main() {
  final source = File('tool/emoji-test.txt').readAsStringSync();
  final groups = parseEmojiTest(source);
  attachShortcodes(groups, emojis);
  File('lib/ui/emoji/emoji_data.dart')
    ..createSync(recursive: true)
    ..writeAsStringSync(renderEmojiTable(groups));
  final count = groups.fold(0, (n, g) => n + g.emoji.length);
  final codes = groups.fold(
    0,
    (n, g) => n + g.emoji.fold(0, (m, e) => m + e.shortcodes.length),
  );
  stdout.writeln('wrote $count emoji in ${groups.length} groups, $codes codes');
}
